# https://docs.docker.com/reference/compose-file/deploy/
services:

  # 포워딩하는 서버의 ip 또는 이름이 정확해야 한다.
  # swarm 에서 실행시키는 stack 이름을 project 라고 명시하면, default.conf 에서는 project_application 으로 사용해야 한다.
  # docker stack deploy -c compose.yml project
  nginx:
    container_name: nginx
    image: nginx:1.22-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx-swarm/conf.d:/etc/nginx/conf.d
      - ./nginx-swarm/nginx.conf:/etc/nginx/nginx.conf

  # docker swarm 에서는 build 와 healthcheck 를 사용할 수 없다.
  # build 대신 image 이름을 명시해야 한다.
  # swarm 이 orchestration 을 제공하기 때문에 healthcheck 는 필요가 없다.
  application:
    container_name: spring
    image: project-application
    ports:
      - 8080:8080
    restart: unless-stopped
    deploy:
      replicas: 2

  mariadb:
    container_name: mariadb
    image: mariadb:11.2
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql:Z
      - ./mariadb/config:/etc/mysql/conf.d
    environment:
      TZ: Asia/Seoul
      MARIADB_DATABASE: mydb
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: username
      MARIADB_PASSWORD: password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 3s
      retries: 10

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Seoul
    healthcheck:
      test: "redis-cli ping"
      interval: 3s
      retries: 10
